version: '3.9'

services:
  rickandmortyapi-service:
    container_name: rickandmortyapi-service
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - rickandmortyapi-network

networks:
  rickandmortyapi-network:
    driver: bridge
